services:
  app:
    build: .
    ports: ["8000:8000"]
    depends_on: [db]
    volumes: [".:/app"]
    environment:
      # Приложение
      - API_HOST=0.0.0.0
      - API_PORT=8000

      # База данных
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=university_db
      - DB_USER=postgres
      - DB_PASSWORD=password

      # Генерация данных
      - DATA_MODE=sample
      - DATA_ABITURIENT_COUNT=10000
      - DATA_FACULTY_COUNT=100
      - DATA_SCHOOL_COUNT=500
      - DATA_GROUP_COUNT=200
      - DATA_STREAM_COUNT=100
      - DATA_SUBJECT_COUNT=50
      - DATA_BATCH_SIZE=1000
    command: main

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: university_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes: [postgres_data:/var/lib/postgresql/data]

volumes:
  postgres_data: